---
branches:
  except:
    - /v\d+\.\d+\.\d+$/
    - /v\d+\.\d+\.\d+-docs$/
cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
dist: xenial
jobs:
  include:
    - stage: dependency-check
      if: "branch =~ /^dependabot\\/(.+)$/ OR branch =~ /^renovate\\/(.+)$/"
      script: "yarn test"
    - stage: prerelease
      if: "branch =~ /^DSY-(\\d+)$/"
      script: "yarn prerelease $TRAVIS_BRANCH && yarn publish"
    - stage: release
      deploy:
        provider: script
        script: "yarn release && yarn publish"
        on:
          branch: master
language: node_js
node_js:
  - lts/*
os: linux
